apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters-kube-prometheus-stacks
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          role: client
  template:
    metadata:
      name: '{{name}}-kube-prometheus-stack'
    spec:
      project: "clients"
      source:
        repoURL: https://github.com/andrewkaczynski/gitops.git
        targetRevision: HEAD
        path: repos/kube-prometheus-stack/19.1.0

        helm:
          releaseName: kube-prometheus-stack
          valueFiles:
          - ../../../clusters/common/applications/kube-prometheus-stack/values.yaml
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true